version: '3'

services:

  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    environment:
      DB_HOST: mysql
      DB_NAME: empty_set
      DB_PASSWORD: password
      DB_USER: root
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    tty: true
    stdin_open: true

  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: empty_set
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites-enabled/app.conf:/etc/nginx/sites-enabled/app.conf:ro
      - ./empty_set/media:/usr/src/app/empty_set/media
      - ./empty_set/static:/usr/src/app/empty_set/static
    ports:
      - "80:80"
    depends_on:
      - python