version: 2
jobs:
  build:
    working_directory: ~/empty_set

    docker:
      - image: circleci/python:3.7
        environment:
          ENVIRONMENT: dev

      - image: circleci/mysql:5.6
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: ubuntu

    steps:
      - checkout
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dev dependencies with pipenv
          command: pipenv install --dev
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          name: Run Django tests
          command: pipenv run coverage run manage.py test -v 2
      - run:
          name: Generate XML test coverage report
          command: pipenv run coverage report && pipenv run coverage xml -o test-reports/coverage.xml
      - run:
          name: Generate HTML test coverage report
          command: pipenv run coverage html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports

notify:
  webhooks:
    - url: https://builds.app-us1.com/circle/notify
    - url: https://builds.staging.app-us1.com/circle/notify
